# Funding options for LoulanKey
# Add your funding options here when available

# github: # Replace with up to 4 GitHub Sponsors-enabled usernames
# patreon: # Replace with a single Patreon username
# open_collective: # Replace with a single Open Collective username
# ko_fi: # Replace with a single Ko-fi username
# custom: # Replace with your custom sponsorship URL
